### ISSUE TITLE
Community Fund Voting History

### ISSUE THREAD

**Issue by chasingkirkjufell** [NavExplorer/navexplorer-frontend#60]
Currently once voting ends, the voting stats are not shown anymore. It would be nice to still have it for future reference and even better if some sort of distribution stats can be displayed. Something like, votes from addresses less than 10k NAV, 10k-100kNAV, 100k - 1mil NAV. So we know how much support a proposal got by which demographic .

**Comment by dantudor** [comment]
Fixed in DAO branch. Demographic breakdown can be pulled out to another ticket
